### ISSUE TITLE
Feature request: list insertion of email addresses

### ISSUE THREAD

**Issue by WorldsEndless** [redguardtoo/counsel-bbdb#2]
It is useful to be able to insert bulk addresses into the To, Cc, Bcc fields (e.g. in message mode). Old solutions do this with reference to BBDB "mail alias" fields, which can be auto-completed to insert all users with that mail alias (http://bbdb.sourceforge.net/bbdb.html#SEC39).

**Comment by redguardtoo** [comment]
I will see what I can do.

**Comment by WorldsEndless** [comment]
I'm trying to use counsel-bbdb-expand-mail-alias and I see that it correctly identifies my aliases, but it doesn't actually insert any thing once I've selected the alias.

**Comment by redguardtoo** [comment]
It's not finished yet. It's still in work branch.

**Comment by redguardtoo** [comment]
f95e481 support mail alias (contact group) (Chen Bin)
