### ISSUE TITLE
No longer installable: "Package lacks a file header"

### ISSUE THREAD

**Issue by mdorman** [redguardtoo/counsel-bbdb#3]
For some reason your last change also removed the first line of `counsel-bbdb.el`:
```
;;; counsel-bbdb.el --- Quick search&input email from BBDB based on ivy
```
Unfortunately, without that, attempts to install the package using `package-install` will get the error "Package lacks a file header".

**Comment by redguardtoo** [comment]
298b48c restore missing file header (Chen Bin)
Thanks for the heads up

**Comment by mdorman** [comment]
Maybe cut a new release with this change?

**Comment by redguardtoo** [comment]
c86f4b9 document updated (Chen Bin)

**Comment by mdorman** [comment]
Cool.
